name: doba_y2k_app
description: DOBA Millenium Set (Port Harcourt Branch) mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  image_picker: ^1.1.2
  http_parser: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/splash.jpg"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/splash.jpg
